version: '3'

services:
  arqsw2-db:
    build: ./Db
    container_name: arqsw2-db
    environment:
      MYSQL_DATABASE: arqsw2
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
    networks:
      - arqsw2

  arqsw2-uba:
    build: ./uba
    container_name: arqsw2-uba
    depends_on:
      arqsw2-db:
        condition: service_healthy
    ports:
      - 8080
    networks:
      - arqsw2
  memcached:
    image: memcached:1.6.16
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - arqsw2

  nginx_uba:
    image: nginx
    container_name: nginx_uba
    volumes:
      - ./uba/nginx/uba.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arqsw2-uba
    ports:
      - "8080:80"
    networks:
      - arqsw2

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - arqsw2 

  arqsw2-hotels:
    build: ./hotels
    container_name: arqsw2-hotels
    depends_on:
      mongo:
        condition: service_started
    ports:
      - 8090
    networks:
      - arqsw2

  nginx_hotels:
    image: nginx
    container_name: nginx_hotels
    volumes:
      - ./hotels/nginx/hotels.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arqsw2-hotels
    ports:
      - "8090:90"
    networks:
      - arqsw2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - arqsw2

  my-solr:
    image: solr:latest
    container_name: my-solr
    ports:
      - "8983:8983"
    networks:
      - arqsw2  

  arqsw2-search2:
    build: ./search2
    container_name: arqsw2-search2
    depends_on:
      rabbitmq:
        condition: service_started
      my-solr:
        condition: service_started
    ports:
      - 8000
    networks:
      - arqsw2        

  nginx_search2:
    image: nginx
    container_name: nginx_search2
    volumes:
      - ./search2/nginx/search2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arqsw2-search2
    ports:
      - "8000:81"
    networks:
      - arqsw2               

networks:
  arqsw2:
    driver: bridge
