version: '3.9'
services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    depends_on:
      - mongo-server
    ports:
      - "8081:8081"